"""
Offcut reuse: when a tile is cut to fit an edge, the leftover piece can
sometimes be reused elsewhere in the layout instead of buying a fresh tile.

This is a greedy heuristic, not an exact solver — greedy first-fit will
occasionally miss a valid reuse a smarter packer would find. Because of
that, callers should always report the raw and reuse-adjusted counts
separately rather than presenting one opaque "tiles to buy" number (see
.plans/tile-layout.md Decisions Log #4).

Only straight (CUT) tiles generate reusable rectangular offcuts. NOTCHED
tiles remove an irregular (non-rectangular) region and are not a source of
reusable offcuts in the MVP.
"""

from dataclasses import dataclass

from .geometry import PlacedTile, Tile, TileKind

_EPS = 1e-6


@dataclass(frozen=True)
class OffcutResult:
    raw_tile_count: int          # one purchased tile per placed piece, no reuse
    reused_count: int            # requirements satisfied from another tile's offcut
    tiles_to_purchase: int       # raw_tile_count - reused_count
    matches: tuple[tuple[int, int], ...]  # (consumer_placed_index, source_placed_index)


def _offcuts_from(index: int, t: PlacedTile) -> list[tuple[float, float, int]]:
    """The rectangular offcut(s) left over from cutting one tile down to `t`.
    A corner tile cut in both directions yields two independent offcuts —
    see the derivation in .plans/tile-layout.md §"offcut reuse"."""
    offcuts: list[tuple[float, float, int]] = []
    if t.width < t.nominal_width - _EPS:
        offcuts.append((t.nominal_width - t.width, t.height, index))
    if t.height < t.nominal_height - _EPS:
        offcuts.append((t.width, t.nominal_height - t.height, index))
    return offcuts


def _fits(offcut_w: float, offcut_h: float, need_w: float, need_h: float, allow_rotation: bool) -> bool:
    straight_fit = offcut_w + _EPS >= need_w and offcut_h + _EPS >= need_h
    rotated_fit = allow_rotation and offcut_h + _EPS >= need_w and offcut_w + _EPS >= need_h
    return straight_fit or rotated_fit


def match_offcuts(placed_tiles: list[PlacedTile], tile: Tile) -> OffcutResult:
    """Greedy first-fit matching of CUT-tile requirements against offcuts
    generated by other CUT tiles in the same layout."""
    raw_tile_count = len(placed_tiles)

    pool: list[tuple[float, float, int]] = []
    for i, t in enumerate(placed_tiles):
        if t.kind == TileKind.CUT:
            pool.extend(_offcuts_from(i, t))

    # Biggest requirements first: they're the pickiest, so give them first
    # refusal on the pool before it's picked over by smaller ones.
    requirements = sorted(
        (
            (i, t.width, t.height)
            for i, t in enumerate(placed_tiles)
            if t.kind == TileKind.CUT
        ),
        key=lambda r: r[1] * r[2],
        reverse=True,
    )
    pool.sort(key=lambda o: o[0] * o[1], reverse=True)

    matches: list[tuple[int, int]] = []
    used_pool_indices: set[int] = set()

    for req_index, need_w, need_h in requirements:
        for pool_index, (offcut_w, offcut_h, source_index) in enumerate(pool):
            if pool_index in used_pool_indices or source_index == req_index:
                continue
            if _fits(offcut_w, offcut_h, need_w, need_h, tile.allow_rotation):
                used_pool_indices.add(pool_index)
                matches.append((req_index, source_index))
                break

    reused_count = len(matches)
    return OffcutResult(
        raw_tile_count=raw_tile_count,
        reused_count=reused_count,
        tiles_to_purchase=raw_tile_count - reused_count,
        matches=tuple(matches),
    )
